version: "3.7"
services:
  myrstudio:
    image: imagename:tag
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
